name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    name: Gerar animação
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.eliseufesantos }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit e Push para a branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
